tokens = [ 
    'PLUS',
    'MINUS',
    'TIMES',
    'DIVIDE',
    'LPAREN',
    'RPAREN',
    'BLOCK_BEGIN',
    'BLOCK_END',
    'STATE_END',
    'IDENTIFIER',
    'FLOAT_CONST',
    'INT_CONST',
    'STRING_CONST',
    'CHARACTER',
    'COLON',
    'COMM',
    'ASSIGN',
    'EQUAL',
    'NEQUAL',
    'GREATER',
    'GEQ',
    'LESS',
    'LEQ',
    'DOT',
    'LBPAREN',
    'RBPAREN',
    'CHOOSE',
    'SUBTYPE',
    'VIEWABLE',
    'EXACTEQ',
    'TILDA',
    'NOT',
    'COMMA',
    'UNDER',
    'AND',
    'OR',
    'AND_BITWISE',
    'OR_BITWISE',
    'FUNTYPE',
    'LOWER_BOUND',
    'UPPER_BOUND',
    'VIEW',
    'INNER_CLASS',
    'AT',
    'QUESTION',
    'TIMES_ASSIGN',
    'DIVIDE_ASSIGN',
    'REMAINDER_ASSIGN',
    'PLUS_ASSIGN',
    'MINUS_ASSIGN',
    'LSHIFT_ASSIGN',
    'RSHIFT_ASSIGN',
    'AND_ASSIGN',
    'OR_ASSIGN',
    'XOR_ASSIGN',
    'XOR',
    'LSHIFT',
    'RSHIFT',
    'REMAINDER', 
]

reserved = {
    'abstract' : 'KWRD_ABST',
    'case' : 'KWRD_CASE',
    'catch' : 'KWRD_CATCH',
    'class' : 'KWRD_CLASS',
    'def' : 'KWRD_DEF',
    'do' : 'KWRD_DO',
    'else' : 'KWRD_ELSE', 
    'extends' : 'KWRD_EXTNDS',
    'false' : 'BOOL_CONSTF',
    'final' : 'KWRD_FINAL',
    'finally' : 'KWRD_FINALLY',
    'for' : 'KWRD_FOR',
    'foreach' : 'KWRD_FOREACH',
    'forsome' : 'KWRD_FORSOME',
    'if' : 'KWRD_IF',
    'implicit' : 'KWRD_IMPLICIT',
    'import' : 'KWRD_IMPORT',
    'lazy' : 'KWRD_LAZY',
    'match' : 'KWRD_MATCH',
    'new' : 'KWRD_NEW',
    'Nil' : 'NIL',
    'null' : 'KWRD_NULL',
    'object' : 'KWRD_OBJECT',
    'override' : 'KWRD_OVERRIDE',
    'package' : 'KWRD_PACKAGE',
    'private' : 'KWRD_PRIVATE',
    'protected' : 'KWRD_PROTECTED',
    'public' : 'KWRD_PUBLIC',
    'return' : 'KWRD_RETURN',
    'sealed' : 'KWRD_SEALED',
    'static' : 'KWRD_STATIC',
    'super' : 'KWRD_SUPER',
    'this' : 'KWRD_THIS',
    'throw' : 'KWRD_THROW',
    'trait' : 'KWRD_TRAIT',
    'try' : 'KWRD_TRY',
    'true' : 'BOOL_CONSTT',
    'type' : 'KWRD_TYPE',
    'until' : 'KWRD_UNTIL',
    'val' : 'KWRD_VAL',
    'var' : 'KWRD_VAR',
    'while' : 'KWRD_WHILE',
    'with' : 'KWRD_WITH',
    'yield' : 'KWRD_YIELD',
    'Int' : 'TYPE_INT',
    'Char' : 'TYPE_CHAR',
    'String' : 'TYPE_STRING',
    'Array' : 'KWRD_ARRAY',
    'macro' : 'KWRD_MACRO'
}

tokens = tokens + list(reserved.values())
